export const busRoutesData = [
    { value: "1", label: "1 - Bronzeville/Union Station" },
    { value: "2", label: "2 - Hyde Park Express" },
    { value: "3", label: "3 - King Drive" },
    { value: "4", label: "4 - Cottage Grove" },
    { value: "X4", label: "X4 - Cottage Grove Express" },
    { value: "5", label: "5 - South Shore Night Bus" },
    { value: "6", label: "6 - Jackson Park Express" },
    { value: "7", label: "7 - Harrison" },
    { value: "8", label: "8 - Halsted" },
    { value: "8A", label: "8A - South Halsted" },
    { value: "9", label: "9 - Ashland" },
    { value: "X9", label: "X9 - Ashland Express" },
    { value: "10", label: "10 - Museum of S & I" },
    { value: "11", label: "11 - Lincoln" },
    { value: "12", label: "12 - Roosevelt" },
    { value: "J14", label: "J14 - Jeffery Jump" },
    { value: "15", label: "15 - Jeffery Local" },
    { value: "18", label: "18 - 16th/18th" },
    { value: "19", label: "19 - United Center Express" },
    { value: "20", label: "20 - Madison" },
    { value: "21", label: "21 - Cermak" },
    { value: "22", label: "22 - Clark" },
    { value: "24", label: "24 - Wentworth" },
    { value: "26", label: "26 - South Shore Express" },
    { value: "28", label: "28 - Stony Island" },
    { value: "29", label: "29 - State" },
    { value: "30", label: "30 - South Chicago" },
    { value: "31", label: "31 - 31st" },
    { value: "34", label: "34 - South Michigan" },
    { value: "35", label: "35 - 31st/35th" },
    { value: "36", label: "36 - Broadway" },
    { value: "37", label: "37 - Sedgwick" },
    { value: "39", label: "39 - Pershing" },
    { value: "43", label: "43 - 43rd" },
    { value: "44", label: "44 - Wallace-Racine" },
    { value: "47", label: "47 - 47th" },
    { value: "48", label: "48 - South Damen" },
    { value: "49", label: "49 - Western" },
    { value: "49B", label: "49B - North Western" },
    { value: "X49", label: "X49 - Western Express" },
    { value: "50", label: "50 - Damen" },
    { value: "51", label: "51 - 51st" },
    { value: "52", label: "52 - Kedzie" },
    { value: "52A", label: "52A - South Kedzie" },
    { value: "53", label: "53 - Pulaski" },
    { value: "53A", label: "53A - South Pulaski" },
    { value: "54", label: "54 - Cicero" },
    { value: "54A", label: "54A - North Cicero/Skokie Blvd." },
    { value: "54B", label: "54B - South Cicero" },
    { value: "55", label: "55 - Garfield" },
    { value: "55A", label: "55A - 55th/Austin" },
    { value: "55N", label: "55N - 55th/Narragansett" },
    { value: "56", label: "56 - Milwaukee" },
    { value: "57", label: "57 - Laramie" },
    { value: "59", label: "59 - 59th/61st" },
    { value: "60", label: "60 - Blue Island/26th" },
    { value: "62", label: "62 - Archer" },
    { value: "62H", label: "62H - Archer/Harlem" },
    { value: "63", label: "63 - 63rd" },
    { value: "63W", label: "63W - West 63rd" },
    { value: "65", label: "65 - Grand" },
    { value: "66", label: "66 - Chicago" },
    { value: "67", label: "67 - 67th-69th-71st" },
    { value: "68", label: "68 - Northwest Highway" },
    { value: "70", label: "70 - Division" },
    { value: "71", label: "71 - 71st/South Shore" },
    { value: "72", label: "72 - North" },
    { value: "73", label: "73 - Armitage" },
    { value: "74", label: "74 - Fullerton" },
    { value: "75", label: "75 - 74th-75th" },
    { value: "76", label: "76 - Diversey" },
    { value: "77", label: "77 - Belmont" },
    { value: "78", label: "78 - Montrose" },
    { value: "79", label: "79 - 79th" },
    { value: "80", label: "80 - Irving Park" },
    { value: "81", label: "81 - Lawrence" },
    { value: "81W", label: "81W - West Lawrence" },
    { value: "82", label: "82 - Kimball-Homan" },
    { value: "84", label: "84 - Peterson" },
    { value: "85", label: "85 - Central" },
    { value: "85A", label: "85A - North Central" },
    { value: "86", label: "86 - Narragansett/Ridgeland" },
    { value: "87", label: "87 - 87th" },
    { value: "88", label: "88 - Higgins" },
    { value: "90", label: "90 - Harlem" },
    { value: "91", label: "91 - Austin" },
    { value: "92", label: "92 - Foster" },
    { value: "93", label: "93 - California/Dodge" },
    { value: "94", label: "94 - California" },
    { value: "95", label: "95 - 95th" },
    { value: "96", label: "96 - Lunt" },
    { value: "97", label: "97 - Skokie" },
    { value: "100", label: "100 - Jeffery Manor Express" },
    { value: "103", label: "103 - West 103rd" },
    { value: "106", label: "106 - East 103rd" },
    { value: "108", label: "108 - Halsted/95th" },
    { value: "111", label: "111 - 111th/King Drive" },
    { value: "111A", label: "111A - Pullman Shuttle" },
    { value: "112", label: "112 - Vincennes/111th" },
    { value: "115", label: "115 - Pullman/115th" },
    { value: "119", label: "119 - Michigan/119th" },
    { value: "120", label: "120 - Ogilvie/Streeterville Express" },
    { value: "121", label: "121 - Union/Streeterville Express" },
    { value: "124", label: "124 - Navy Pier" },
    { value: "125", label: "125 - Water Tower Express" },
    { value: "126", label: "126 - Jackson" },
    { value: "130", label: "130 - Museum Campus" },
    { value: "134", label: "134 - Stockton/LaSalle Express" },
    { value: "135", label: "135 - Clarendon/LaSalle Express" },
    { value: "136", label: "136 - Sheridan/LaSalle Express" },
    { value: "143", label: "143 - Stockton/Michigan Express" },
    { value: "146", label: "146 - Inner Lake Shore/Michigan Exp." },
    { value: "147", label: "147 - Outer DuSable Lake Shore Exp." },
    { value: "148", label: "148 - Clarendon/Michigan Express" },
    { value: "151", label: "151 - Sheridan" },
    { value: "152", label: "152 - Addison" },
    { value: "155", label: "155 - Devon" },
    { value: "156", label: "156 - LaSalle" },
    { value: "157", label: "157 - Streeterville/Taylor" },
    { value: "165", label: "165 - West 65th" },
    { value: "169", label: "169 - 69th-UPS Express" },
    { value: "171", label: "171 - U. of Chicago/Hyde Park" },
    { value: "172", label: "172 - U. of Chicago/Kenwood" },
    { value: "192", label: "192 - U. of Chicago Hospitals Express" },
    { value: "201", label: "201 - Central/Ridge" },
    { value: "206", label: "206 - Evanston Circulator" }
];

export const trainRoutesData = [
    {value: "Red", label: "Red Line"},
    {value: "Blue", label:"Blue Line"},
    {value: "Brn", label: "Brown Line"},
    {value: "G", label: "Green Line"},
    {value: "Org", label: "Orange Line"},
    {value: "P", label: "Purple Line"},
    {value: "Pink", label: "Pink Line"},
    {value: "Y", label: "Yellow Line"}
];

export const trainDirectionData = [
    { value: "Red",  label: ["Howard", "95th/Dan Ryan"] },
    { value: "Blue", label: ["O'Hare", "Forest Park"] },
    { value: "Brn",  label: ["Kimball", "Loop"] },
    { value: "G",    label: ["Harlem/Lake", "South"] },
    //what south means above is Ashland/63rd OR Cottage Grove
    { value: "Org",  label: ["Loop", "Midway"] },
    { value: "P",    label: ["Linden", "Howard or Loop"] },
    { value: "Pink", label: ["Loop", "54th/Cermak"] },
    { value: "Y",    label: ["Skokie", "Howard"] },
];